# Generated by Django 5.1.5 on 2025-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0002_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='itinerary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
