# Generated by Django 5.1.5 on 2025-03-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trvels', '0003_location_itinerary_delete_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='itinerary',
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDate', models.DateField()),
                ('day', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='Trvels.location')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
